version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - rag_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      - rag_network
    command: python frontend.py
    environment:
      BACKEND_URL: http://backend:8000

networks:
  rag_network:
    driver: bridge
